### ISSUE TITLE
`entryNames: '[dir]/[name]'` breaks plugin-html

### ISSUE THREAD

**Issue by paulirish** [chialab/rna#49]
this line in my esbuild config...  `entryNames: '[dir]/[name]',`
 along with the html plugin... gets me this exception:

```

✘ [ERROR] [plugin html] ENOENT: no such file or directory, copyfile 'proj/packages/viewer/dist/assets/index-LCFOZCXA.html' -> 'proj/packages/viewer/dist/[dir]/index.html'

  This error came from the "onEnd" callback registered here:

    proj/node_modules/esbuild/lib/main.js:814:22:
      814 │         let promise = setup({
          ╵                       ^

    at setup (file://proj/node_modules/@chialab/esbuild-plugin-html/dist/index.js:60:162521)
    at handlePlugins (proj/node_modules/esbuild/lib/main.js:814:23)
    at Object.buildOrServe (proj/node_modules/esbuild/lib/main.js:1108:7)
    at proj/node_modules/esbuild/lib/main.js:1961:17
    at new Promise (<anonymous>)
    at Object.build (proj/node_modules/esbuild/lib/main.js:1960:14)
    at Object.build (proj/node_modules/esbuild/lib/main.js:1814:51)
    at main (proj/scripts/build-app.js:147:32)

Error: Build failed with 1 error:
error: ENOENT: no such file or directory, copyfile 'proj/packages/viewer/dist/assets/index-LCFOZCXA.html' -> 'proj/packages/viewer/dist/[dir]/index.html'
    at failureErrorWithLog (proj/node_modules/esbuild/lib/main.js:1557:15)
    at proj/node_modules/esbuild/lib/main.js:1215:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      pluginName: 'html',
      text: "ENOENT: no such file or directory, copyfile 'proj/packages/viewer/dist/assets/index-LCFOZCXA.html' -> 'proj/packages/viewer/dist/[dir]/index.html'",
      location: null,
      notes: [Array],
      detail: [Error]
    }
  ],
  warnings: []
}
```

clearly the `[dir]/` bit isn't being resolved.

interestingly, `[dir]/` in `assetNames works fine, though... it does lead to some weird directory structures.. :)
![image](https://user-images.githubusercontent.com/39191/166078422-ae6eaf3e-7c77-4a66-9579-e219ddfe6afe.png)

**Comment by edoardocavazza** [comment]
Hello @paulirish, thanks for the issue. Can you check if version 0.15.17 solves your problem?
